services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebConsulting\WorkosAuth\:
    resource: '../Classes/*'

  WebConsulting\WorkosAuth\Controller\Backend\SetupAssistantController:
    public: true

  WebConsulting\WorkosAuth\Controller\Backend\UserManagementController:
    public: true

  WebConsulting\WorkosAuth\Controller\Frontend\LoginController:
    public: true

  WebConsulting\WorkosAuth\Controller\Frontend\AccountController:
    public: true

  WebConsulting\WorkosAuth\Controller\Frontend\TeamController:
    public: true

  WebConsulting\WorkosAuth\LoginProvider\WorkosBackendLoginProvider:
    public: true

  WebConsulting\WorkosAuth\Authentication\WorkosTypo3AuthenticationService:
    public: true

  WebConsulting\WorkosAuth\Middleware\FrontendWorkosAuthMiddleware:
    public: true

  WebConsulting\WorkosAuth\Middleware\BackendWorkosAuthMiddleware:
    public: true
